<?php


namespace app\models;


use app\core\Model;

class UserModel extends Model
{
    public string $username;
    public string $email;
    public string $password;

    public function tableName(): string
    {
        return 'users';
    }

    public function attributes(): array
    {
        return ['email', 'password'];
    }

    public function create()
    {
        return parent::create(); // TODO: Change the autogenerated stub
    }

}